#!/bin/bash

# Rydex Environment Setup Script
# This script helps set up environment variables for different deployment platforms

echo "🚀 Rydex Deployment Environment Setup"
echo "====================================="

# Check if .env.production.example exists
if [ ! -f ".env.production.example" ]; then
    echo "❌ .env.production.example not found!"
    exit 1
fi

echo "✅ Found .env.production.example"
echo ""
echo "📋 Please provide the following information:"
echo ""

# Collect user input
read -p "Vercel Frontend URL (https://your-app.vercel.app): " VERCEL_URL
read -p "Render Backend URL (https://your-backend.onrender.com): " BACKEND_URL
read -p "Render Socket Server URL (https://your-socketserver.onrender.com): " SOCKET_URL
read -p "PostgreSQL Connection String: " POSTGRES_URL
read -p "MongoDB Connection String: " MONGO_URL
read -p "Redis Connection String: " REDIS_URL
read -p "JWT Secret: " JWT_SECRET
read -p "NextAuth Secret: " NEXTAUTH_SECRET
read -p "Stripe Publishable Key: " STRIPE_PUB_KEY
read -p "Stripe Secret Key: " STRIPE_SECRET_KEY
read -p "Cloudinary Cloud Name: " CLOUDINARY_NAME
read -p "Cloudinary API Key: " CLOUDINARY_API_KEY
read -p "Cloudinary API Secret: " CLOUDINARY_API_SECRET
read -p "OpenAI API Key: " OPENAI_API_KEY
read -p "Google AI API Key: " GOOGLE_AI_API_KEY

# Create .env.production file
cat > .env.production << EOF
# Production Environment Variables
# Generated by setup script

# URLs
NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL
NEXT_PUBLIC_APP_URL=$VERCEL_URL
NEXTAUTH_URL=$VERCEL_URL
NEXT_PUBLIC_SOCKET_URL=$SOCKET_URL

# Database
MONGODB_URL=$MONGO_URL
REDIS_URL=$REDIS_URL
SPRING_DATASOURCE_URL=jdbc:postgresql://$POSTGRES_URL

# Authentication
JWT_SECRET=$JWT_SECRET
NEXTAUTH_SECRET=$NEXTAUTH_SECRET

# Payment
STRIPE_PUBLISHABLE_KEY=$STRIPE_PUB_KEY
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

# Cloud Storage
CLOUDINARY_CLOUD_NAME=$CLOUDINARY_NAME
CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

# AI Services
OPENAI_API_KEY=$OPENAI_API_KEY
GOOGLE_AI_API_KEY=$GOOGLE_AI_API_KEY
EOF

echo ""
echo "✅ Created .env.production file"
echo ""
echo "📋 Copy these values to your deployment platforms:"
echo ""
echo "=== VERCEL ENVIRONMENT VARIABLES ==="
echo "NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL"
echo "NEXT_PUBLIC_APP_URL=$VERCEL_URL"
echo "NEXTAUTH_URL=$VERCEL_URL"
echo "MONGODB_URL=$MONGO_URL"
echo "NEXT_PUBLIC_SOCKET_URL=$SOCKET_URL"
echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
echo "JWT_SECRET=$JWT_SECRET"
echo "STRIPE_PUBLISHABLE_KEY=$STRIPE_PUB_KEY"
echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY"
echo "CLOUDINARY_CLOUD_NAME=$CLOUDINARY_NAME"
echo "CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY"
echo "CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET"
echo "OPENAI_API_KEY=$OPENAI_API_KEY"
echo "GOOGLE_AI_API_KEY=$GOOGLE_AI_API_KEY"
echo ""
echo "=== RENDER BACKEND ENVIRONMENT VARIABLES ==="
echo "SPRING_DATASOURCE_URL=jdbc:postgresql://$POSTGRES_URL"
echo "DATABASE_USERNAME=rydex_user"
echo "DATABASE_PASSWORD=[YOUR_POSTGRES_PASSWORD]"
echo "JWT_SECRET=$JWT_SECRET"
echo "NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL"
echo "NEXT_PUBLIC_APP_URL=$VERCEL_URL"
echo "MONGODB_URL=$MONGO_URL"
echo "SPRING_PROFILES_ACTIVE=prod"
echo ""
echo "=== RENDER SOCKET SERVER ENVIRONMENT VARIABLES ==="
echo "MONGODB_URL=$MONGO_URL"
echo "REDIS_URL=$REDIS_URL"
echo "NEXT_BASE_URL=$VERCEL_URL"
echo "PORT=10000"
echo ""
echo "🎉 Setup complete! Follow the deployment guide in DEPLOYMENT.md"